### ISSUE TITLE
cifar10 configuration

### ISSUE THREAD

**Issue by xjturobocon** [XuZhengzhuo/LiVT#3]
Hi, I can not reproduce cifa10-LT result in your paper, Can you share me with the configuration of cifa-10-LT? thank you!

**Comment by XuZhengzhuo** [comment]
You can adopt this setting for CIFAR10-LT-10:
```python
def finetune():
    T = Trainer()
    T.task = 'debug'
    T.note = 'debug'
    T.ckpt = '/home/hfx/LiVT/ckpt/pretrain/ImageNet-LT/vit_base_224/checkpoint.pth'

    T.dataset = 'cifar10-LT'
    T.nb_classes = 10
    T.imbf = 10
    
    T.epochs = 20
    T.device = '0,1,2,3'

    T.batch = 64
    T.accum_iter = 8

    T.model = 'vit_base_patch16'
    T.input_size = 64
    T.drop_path = 0.1

    T.clip_grad = None
    T.weight_decay = 0.05
    T.adamW2 = 0.999

    T.lr = None
    T.blr = 1e-3
    T.layer_decay = 0.65
    T.min_lr = 1e-6
    T.warmup_epochs = 5

    T.color_jitter = None
    T.aa = 'rand-m9-mstd0.5-inc1'

    T.reprob = 0.25
    T.remode = 'pixel'
    T.recount = 1
    T.resplit = False

    T.mixup = 0.8
    T.cutmix = 1.
    T.cutmix_minmax = None
    T.mixup_prob = 1.0
    T.mixup_switch_prob = 0.5
    T.mixup_mode = 'batch'

    T.loss = 'Bal_BCE'
    T.bal_tau = 1.0
    T.smoothing = 0.1

    T.global_pool = True

    T.seed = 0
    T.prit = 1

    T.num_workers = 16
    T.master_port = 29500

    T.finetune()
```

Here is my log:
```
job dir: /home/hfx/LiVT
Namespace(aa='rand-m9-mstd0.5-inc1',
accum_iter=8,
adamW2=0.999,
attn_only=False,
bal_tau=1.0,
batch_size=64,
blr=0.001,
ckpt_dir='/home/hfx/LiVT/ckpt/debug/cifar10-LT/vit_base_patch16/debug',
clip_grad=None,
color_jitter=None,
cutmix=1.0,
cutmix_minmax=None,
data_path='/myDATA',
dataset='cifar10-LT',
device='cuda',
dist_backend='nccl',
dist_eval=True,
dist_on_itp=False,
dist_url='env://',
distributed=True,
drop_path=0.1,
epochs=20,
eval=False,
finetune='/home/hfx/LiVT/ckpt/pretrain/ImageNet-LT/vit_base_224/checkpoint.pth',
global_pool=True,
gpu=0,
imbf=10,
input_size=64,
layer_decay=0.65,
local_rank=0,
log_dir='/home/hfx/LiVT/exp/debug/cifar10-LT/vit_base_patch16/debug',
loss='Bal_BCE',
lr=None,
min_lr=1e-06,
mixup=0.8,
mixup_mode='batch',
mixup_prob=1.0,
mixup_switch_prob=0.5,
model='vit_base_patch16',
nb_classes=10,
num_workers=16,
pin_mem=True,
prit=1,
rank=0,
recount=1,
remode='pixel',
reprob=0.25,
resplit=False,
resume='',
seed=0,
smoothing=0.0,
start_epoch=0,
warmup_epochs=5,
weight_decay=0.05,
world_size=4)
Sampler_train = <torch.utils.data.distributed.DistributedSampler object at 0x7f10cb992bd0>
Train on 20431 Image w.r.t. 10 classes
Load pre-trained checkpoint from: /home/hfx/LiVT/ckpt/pretrain/ImageNet-LT/vit_base_224/checkpoint.pth
Removing key head.weight from pretrained checkpoint
Removing key head.bias from pretrained checkpoint
_IncompatibleKeys(missing_keys=['head.weight', 'head.bias'], unexpected_keys=[])
Model = vit_base_patch16
number of params (M): 85.67
base lr: 1.00e-03
actual lr: 8.00e-03
accumulate grad iterations: 8
effective batch size: 2048
Mixup is activated!
criterion = BCE_loss()
Start training for 20 epochs
Accuracy of the network on the 10000 test images: 48.6%
Max accuracy: 48.61%
{"train_lr": 0.0007198846338727768, "train_loss": 2.8714588020421283, "test_loss": 1.4898320838809014, "test_acc1": 48.61, "test_acc5": 95.28, "epoch": 0, "n_parameters": 85668106}
Training epoch 0 for 0:00:35
Accuracy of the network on the 10000 test images: 72.2%
Max accuracy: 72.18%
{"train_lr": 0.002319884633872777, "train_loss": 2.5772250951090947, "test_loss": 0.8367310775443911, "test_acc1": 72.18, "test_acc5": 98.64, "epoch": 1, "n_parameters": 85668106}
Training epoch 1 for 0:00:35
Accuracy of the network on the 10000 test images: 79.2%
Max accuracy: 79.19%
{"train_lr": 0.003919884633872775, "train_loss": 2.3542069988914682, "test_loss": 0.6063723633997142, "test_acc1": 79.19, "test_acc5": 98.99, "epoch": 2, "n_parameters": 85668106}
Training epoch 2 for 0:00:34
Accuracy of the network on the 10000 test images: 82.5%
Max accuracy: 82.55%
{"train_lr": 0.005519884633872775, "train_loss": 2.285645261218276, "test_loss": 0.5343093725852668, "test_acc1": 82.55, "test_acc5": 99.22, "epoch": 3, "n_parameters": 85668106}
Training epoch 3 for 0:00:34
Accuracy of the network on the 10000 test images: 82.9%
Max accuracy: 82.89%
{"train_lr": 0.0071198846338727815, "train_loss": 2.275628869669347, "test_loss": 0.5361176945501939, "test_acc1": 82.89, "test_acc5": 99.05, "epoch": 4, "n_parameters": 85668106}
Training epoch 4 for 0:00:34
Accuracy of the network on the 10000 test images: 83.3%
Max accuracy: 83.26%
{"train_lr": 0.0079750105162023, "train_loss": 2.2382743656635284, "test_loss": 0.4976317548193038, "test_acc1": 83.26, "test_acc5": 99.31, "epoch": 5, "n_parameters": 85668106}
Training epoch 5 for 0:00:34
Accuracy of the network on the 10000 test images: 86.4%
Max accuracy: 86.38%
{"train_lr": 0.007810058012392656, "train_loss": 2.201795018549207, "test_loss": 0.41293818820267914, "test_acc1": 86.38, "test_acc5": 99.58, "epoch": 6, "n_parameters": 85668106}
Training epoch 6 for 0:00:35
Accuracy of the network on the 10000 test images: 87.4%
Max accuracy: 87.41%
{"train_lr": 0.007478609543153936, "train_loss": 2.2257936329026764, "test_loss": 0.39771946768742056, "test_acc1": 87.41, "test_acc5": 99.45, "epoch": 7, "n_parameters": 85668106}
Training epoch 7 for 0:00:34
Accuracy of the network on the 10000 test images: 87.5%
Max accuracy: 87.48%
{"train_lr": 0.006995150997058096, "train_loss": 2.1597310112246983, "test_loss": 0.38140167636447586, "test_acc1": 87.48, "test_acc5": 99.58, "epoch": 8, "n_parameters": 85668106}
Training epoch 8 for 0:00:34
Accuracy of the network on the 10000 test images: 88.7%
Max accuracy: 88.72%
{"train_lr": 0.006380811832461018, "train_loss": 2.1425217507006247, "test_loss": 0.349570360861253, "test_acc1": 88.72, "test_acc5": 99.63, "epoch": 9, "n_parameters": 85668106}
Training epoch 9 for 0:00:34
Accuracy of the network on the 10000 test images: 89.6%
Max accuracy: 89.63%
{"train_lr": 0.005662441618781968, "train_loss": 2.1418888795224924, "test_loss": 0.32572711488464845, "test_acc1": 89.63, "test_acc5": 99.68, "epoch": 10, "n_parameters": 85668106}
Training epoch 10 for 0:00:34
Accuracy of the network on the 10000 test images: 89.7%
Max accuracy: 89.73%
{"train_lr": 0.004871436581481463, "train_loss": 2.0355309591263153, "test_loss": 0.320286868698895, "test_acc1": 89.73, "test_acc5": 99.64, "epoch": 11, "n_parameters": 85668106}
Training epoch 11 for 0:00:35
Accuracy of the network on the 10000 test images: 89.7%
Max accuracy: 89.73%
{"train_lr": 0.004042367436352819, "train_loss": 2.030491162893138, "test_loss": 0.3182535513420589, "test_acc1": 89.68, "test_acc5": 99.62, "epoch": 12, "n_parameters": 85668106}
Training epoch 12 for 0:00:27
Accuracy of the network on the 10000 test images: 90.3%
Max accuracy: 90.30%
{"train_lr": 0.003211468483353306, "train_loss": 2.127987779582603, "test_loss": 0.30006673122989014, "test_acc1": 90.3, "test_acc5": 99.7, "epoch": 13, "n_parameters": 85668106}
Training epoch 13 for 0:00:35
Accuracy of the network on the 10000 test images: 90.5%
Max accuracy: 90.52%
{"train_lr": 0.0024150539938245447, "train_loss": 2.0666654892737353, "test_loss": 0.29293982569361104, "test_acc1": 90.52, "test_acc5": 99.66, "epoch": 14, "n_parameters": 85668106}
Training epoch 14 for 0:00:38
Accuracy of the network on the 10000 test images: 91.0%
Max accuracy: 91.05%
{"train_lr": 0.0016879311025796608, "train_loss": 2.0121927632938457, "test_loss": 0.28423637461382895, "test_acc1": 91.05, "test_acc5": 99.66, "epoch": 15, "n_parameters": 85668106}
Training epoch 15 for 0:00:37
Accuracy of the network on the 10000 test images: 91.2%
Max accuracy: 91.25%
{"train_lr": 0.0010618785690888015, "train_loss": 2.035297965513, "test_loss": 0.27344376463443043, "test_acc1": 91.25, "test_acc5": 99.75, "epoch": 16, "n_parameters": 85668106}
Training epoch 16 for 0:00:38
Accuracy of the network on the 10000 test images: 91.2%
Max accuracy: 91.25%
{"train_lr": 0.0005642578931988751, "train_loss": 2.045497215624097, "test_loss": 0.2700254609982949, "test_acc1": 91.24, "test_acc5": 99.72, "epoch": 17, "n_parameters": 85668106}
Training epoch 17 for 0:00:27
Accuracy of the network on the 10000 test images: 91.3%
Max accuracy: 91.27%
{"train_lr": 0.00021681748629520515, "train_loss": 2.007395812605001, "test_loss": 0.270625050237868, "test_acc1": 91.27, "test_acc5": 99.74, "epoch": 18, "n_parameters": 85668106}
Training epoch 18 for 0:00:35
Accuracy of the network on the 10000 test images: 91.3%
Max accuracy: 91.28%
{"train_lr": 3.4742161363524e-05, "train_loss": 2.038420892025851, "test_loss": 0.2704039338335861, "test_acc1": 91.28, "test_acc5": 99.74, "epoch": 19, "n_parameters": 85668106}
Training epoch 19 for 0:00:34
Total training time 0:11:34
```

**Comment by 1170300714** [comment]
> You can adopt this setting for CIFAR10-LT-10:
> 
> ```python
> def finetune():
>     T = Trainer()
>     T.task = 'debug'
>     T.note = 'debug'
>     T.ckpt = '/home/hfx/LiVT/ckpt/pretrain/ImageNet-LT/vit_base_224/checkpoint.pth'
> 
>     T.dataset = 'cifar10-LT'
>     T.nb_classes = 10
>     T.imbf = 10
>     
>     T.epochs = 20
>     T.device = '0,1,2,3'
> 
>     T.batch = 64
>     T.accum_iter = 8
> 
>     T.model = 'vit_base_patch16'
>     T.input_size = 64
>     T.drop_path = 0.1
> 
>     T.clip_grad = None
>     T.weight_decay = 0.05
>     T.adamW2 = 0.999
> 
>     T.lr = None
>     T.blr = 1e-3
>     T.layer_decay = 0.65
>     T.min_lr = 1e-6
>     T.warmup_epochs = 5
> 
>     T.color_jitter = None
>     T.aa = 'rand-m9-mstd0.5-inc1'
> 
>     T.reprob = 0.25
>     T.remode = 'pixel'
>     T.recount = 1
>     T.resplit = False
> 
>     T.mixup = 0.8
>     T.cutmix = 1.
>     T.cutmix_minmax = None
>     T.mixup_prob = 1.0
>     T.mixup_switch_prob = 0.5
>     T.mixup_mode = 'batch'
> 
>     T.loss = 'Bal_BCE'
>     T.bal_tau = 1.0
>     T.smoothing = 0.1
> 
>     T.global_pool = True
> 
>     T.seed = 0
>     T.prit = 1
> 
>     T.num_workers = 16
>     T.master_port = 29500
> 
>     T.finetune()
> ```
> 
> Here is my log:
> 
> ```
> job dir: /home/hfx/LiVT
> Namespace(aa='rand-m9-mstd0.5-inc1',
> accum_iter=8,
> adamW2=0.999,
> attn_only=False,
> bal_tau=1.0,
> batch_size=64,
> blr=0.001,
> ckpt_dir='/home/hfx/LiVT/ckpt/debug/cifar10-LT/vit_base_patch16/debug',
> clip_grad=None,
> color_jitter=None,
> cutmix=1.0,
> cutmix_minmax=None,
> data_path='/myDATA',
> dataset='cifar10-LT',
> device='cuda',
> dist_backend='nccl',
> dist_eval=True,
> dist_on_itp=False,
> dist_url='env://',
> distributed=True,
> drop_path=0.1,
> epochs=20,
> eval=False,
> finetune='/home/hfx/LiVT/ckpt/pretrain/ImageNet-LT/vit_base_224/checkpoint.pth',
> global_pool=True,
> gpu=0,
> imbf=10,
> input_size=64,
> layer_decay=0.65,
> local_rank=0,
> log_dir='/home/hfx/LiVT/exp/debug/cifar10-LT/vit_base_patch16/debug',
> loss='Bal_BCE',
> lr=None,
> min_lr=1e-06,
> mixup=0.8,
> mixup_mode='batch',
> mixup_prob=1.0,
> mixup_switch_prob=0.5,
> model='vit_base_patch16',
> nb_classes=10,
> num_workers=16,
> pin_mem=True,
> prit=1,
> rank=0,
> recount=1,
> remode='pixel',
> reprob=0.25,
> resplit=False,
> resume='',
> seed=0,
> smoothing=0.0,
> start_epoch=0,
> warmup_epochs=5,
> weight_decay=0.05,
> world_size=4)
> Sampler_train = <torch.utils.data.distributed.DistributedSampler object at 0x7f10cb992bd0>
> Train on 20431 Image w.r.t. 10 classes
> Load pre-trained checkpoint from: /home/hfx/LiVT/ckpt/pretrain/ImageNet-LT/vit_base_224/checkpoint.pth
> Removing key head.weight from pretrained checkpoint
> Removing key head.bias from pretrained checkpoint
> _IncompatibleKeys(missing_keys=['head.weight', 'head.bias'], unexpected_keys=[])
> Model = vit_base_patch16
> number of params (M): 85.67
> base lr: 1.00e-03
> actual lr: 8.00e-03
> accumulate grad iterations: 8
> effective batch size: 2048
> Mixup is activated!
> criterion = BCE_loss()
> Start training for 20 epochs
> Accuracy of the network on the 10000 test images: 48.6%
> Max accuracy: 48.61%
> {"train_lr": 0.0007198846338727768, "train_loss": 2.8714588020421283, "test_loss": 1.4898320838809014, "test_acc1": 48.61, "test_acc5": 95.28, "epoch": 0, "n_parameters": 85668106}
> Training epoch 0 for 0:00:35
> Accuracy of the network on the 10000 test images: 72.2%
> Max accuracy: 72.18%
> {"train_lr": 0.002319884633872777, "train_loss": 2.5772250951090947, "test_loss": 0.8367310775443911, "test_acc1": 72.18, "test_acc5": 98.64, "epoch": 1, "n_parameters": 85668106}
> Training epoch 1 for 0:00:35
> Accuracy of the network on the 10000 test images: 79.2%
> Max accuracy: 79.19%
> {"train_lr": 0.003919884633872775, "train_loss": 2.3542069988914682, "test_loss": 0.6063723633997142, "test_acc1": 79.19, "test_acc5": 98.99, "epoch": 2, "n_parameters": 85668106}
> Training epoch 2 for 0:00:34
> Accuracy of the network on the 10000 test images: 82.5%
> Max accuracy: 82.55%
> {"train_lr": 0.005519884633872775, "train_loss": 2.285645261218276, "test_loss": 0.5343093725852668, "test_acc1": 82.55, "test_acc5": 99.22, "epoch": 3, "n_parameters": 85668106}
> Training epoch 3 for 0:00:34
> Accuracy of the network on the 10000 test images: 82.9%
> Max accuracy: 82.89%
> {"train_lr": 0.0071198846338727815, "train_loss": 2.275628869669347, "test_loss": 0.5361176945501939, "test_acc1": 82.89, "test_acc5": 99.05, "epoch": 4, "n_parameters": 85668106}
> Training epoch 4 for 0:00:34
> Accuracy of the network on the 10000 test images: 83.3%
> Max accuracy: 83.26%
> {"train_lr": 0.0079750105162023, "train_loss": 2.2382743656635284, "test_loss": 0.4976317548193038, "test_acc1": 83.26, "test_acc5": 99.31, "epoch": 5, "n_parameters": 85668106}
> Training epoch 5 for 0:00:34
> Accuracy of the network on the 10000 test images: 86.4%
> Max accuracy: 86.38%
> {"train_lr": 0.007810058012392656, "train_loss": 2.201795018549207, "test_loss": 0.41293818820267914, "test_acc1": 86.38, "test_acc5": 99.58, "epoch": 6, "n_parameters": 85668106}
> Training epoch 6 for 0:00:35
> Accuracy of the network on the 10000 test images: 87.4%
> Max accuracy: 87.41%
> {"train_lr": 0.007478609543153936, "train_loss": 2.2257936329026764, "test_loss": 0.39771946768742056, "test_acc1": 87.41, "test_acc5": 99.45, "epoch": 7, "n_parameters": 85668106}
> Training epoch 7 for 0:00:34
> Accuracy of the network on the 10000 test images: 87.5%
> Max accuracy: 87.48%
> {"train_lr": 0.006995150997058096, "train_loss": 2.1597310112246983, "test_loss": 0.38140167636447586, "test_acc1": 87.48, "test_acc5": 99.58, "epoch": 8, "n_parameters": 85668106}
> Training epoch 8 for 0:00:34
> Accuracy of the network on the 10000 test images: 88.7%
> Max accuracy: 88.72%
> {"train_lr": 0.006380811832461018, "train_loss": 2.1425217507006247, "test_loss": 0.349570360861253, "test_acc1": 88.72, "test_acc5": 99.63, "epoch": 9, "n_parameters": 85668106}
> Training epoch 9 for 0:00:34
> Accuracy of the network on the 10000 test images: 89.6%
> Max accuracy: 89.63%
> {"train_lr": 0.005662441618781968, "train_loss": 2.1418888795224924, "test_loss": 0.32572711488464845, "test_acc1": 89.63, "test_acc5": 99.68, "epoch": 10, "n_parameters": 85668106}
> Training epoch 10 for 0:00:34
> Accuracy of the network on the 10000 test images: 89.7%
> Max accuracy: 89.73%
> {"train_lr": 0.004871436581481463, "train_loss": 2.0355309591263153, "test_loss": 0.320286868698895, "test_acc1": 89.73, "test_acc5": 99.64, "epoch": 11, "n_parameters": 85668106}
> Training epoch 11 for 0:00:35
> Accuracy of the network on the 10000 test images: 89.7%
> Max accuracy: 89.73%
> {"train_lr": 0.004042367436352819, "train_loss": 2.030491162893138, "test_loss": 0.3182535513420589, "test_acc1": 89.68, "test_acc5": 99.62, "epoch": 12, "n_parameters": 85668106}
> Training epoch 12 for 0:00:27
> Accuracy of the network on the 10000 test images: 90.3%
> Max accuracy: 90.30%
> {"train_lr": 0.003211468483353306, "train_loss": 2.127987779582603, "test_loss": 0.30006673122989014, "test_acc1": 90.3, "test_acc5": 99.7, "epoch": 13, "n_parameters": 85668106}
> Training epoch 13 for 0:00:35
> Accuracy of the network on the 10000 test images: 90.5%
> Max accuracy: 90.52%
> {"train_lr": 0.0024150539938245447, "train_loss": 2.0666654892737353, "test_loss": 0.29293982569361104, "test_acc1": 90.52, "test_acc5": 99.66, "epoch": 14, "n_parameters": 85668106}
> Training epoch 14 for 0:00:38
> Accuracy of the network on the 10000 test images: 91.0%
> Max accuracy: 91.05%
> {"train_lr": 0.0016879311025796608, "train_loss": 2.0121927632938457, "test_loss": 0.28423637461382895, "test_acc1": 91.05, "test_acc5": 99.66, "epoch": 15, "n_parameters": 85668106}
> Training epoch 15 for 0:00:37
> Accuracy of the network on the 10000 test images: 91.2%
> Max accuracy: 91.25%
> {"train_lr": 0.0010618785690888015, "train_loss": 2.035297965513, "test_loss": 0.27344376463443043, "test_acc1": 91.25, "test_acc5": 99.75, "epoch": 16, "n_parameters": 85668106}
> Training epoch 16 for 0:00:38
> Accuracy of the network on the 10000 test images: 91.2%
> Max accuracy: 91.25%
> {"train_lr": 0.0005642578931988751, "train_loss": 2.045497215624097, "test_loss": 0.2700254609982949, "test_acc1": 91.24, "test_acc5": 99.72, "epoch": 17, "n_parameters": 85668106}
> Training epoch 17 for 0:00:27
> Accuracy of the network on the 10000 test images: 91.3%
> Max accuracy: 91.27%
> {"train_lr": 0.00021681748629520515, "train_loss": 2.007395812605001, "test_loss": 0.270625050237868, "test_acc1": 91.27, "test_acc5": 99.74, "epoch": 18, "n_parameters": 85668106}
> Training epoch 18 for 0:00:35
> Accuracy of the network on the 10000 test images: 91.3%
> Max accuracy: 91.28%
> {"train_lr": 3.4742161363524e-05, "train_loss": 2.038420892025851, "test_loss": 0.2704039338335861, "test_acc1": 91.28, "test_acc5": 99.74, "epoch": 19, "n_parameters": 85668106}
> Training epoch 19 for 0:00:34
> Total training time 0:11:34
> ```

Hi~, I notice that cifar-10-lt setting use the ckpt pretrained on ImageNet-lt, not on cifar-10-lt itself, is it?

**Comment by XuZhengzhuo** [comment]
Yes, and we have stated this in the main text description of Table 7. :-)

**Comment by 1170300714** [comment]
收到，感谢您的来件

**Comment by 1170300714** [comment]
> Yes, and we have stated this in the main text description of Table 7. :-)

Thanks for the reply! BTW, could you share the  MGP pretrained model on ImageNet-1K? Thanks！
