### ISSUE TITLE
Problems loading the provided ckpt

### ISSUE THREAD

**Issue by RuoxiangXu** [XuZhengzhuo/LiVT#4]
Hi, thanks for your great work.
I have downloaded your ImageNet-LT 224*224 checkpoint file, but I am encountering errors when attempting to load the state to a vit base 16 model. 
It seems that the given keys in the checkpoint file don't match those of the vit model's.
The error is like this:
```
RuntimeError: Error(s) in loading state_dict for VisionTransformer:
	Missing key(s) in state_dict: "norm.weight", "norm.bias". 
	Unexpected key(s) in state_dict: "fc_norm.weight", "fc_norm.bias".
```

Here is the code:
```python
import torch
from vit import *

checkpoint = torch.load('checkpoint.pth', map_location=torch.device('cpu'))
vit = vit_base_patch16()
vit.load_state_dict(checkpoint['model'])
```
The "vit" here is exactly the vit.py file in your repository.

Could you please provide some guidance on how to resolve this issue?
Any comment will be kindly appreciated!

**Comment by XuZhengzhuo** [comment]
Note the distinction between pre-trained models (with the mae decoder) and fine-tuned models (with the classifier).  The models loaded into vit base 16 should be fine-tuned ones.  

In fact, you can ignore this check and just comment out the code:
https://github.com/XuZhengzhuo/LiVT/blob/main/main_finetune.py#L259-L262
