### ISSUE TITLE
Dataset Configuration

### ISSUE THREAD

**Issue by ReIDResman** [XuZhengzhuo/LiVT#5]
Thanks for the great work and I do really appreciate it. I am trying to reproduce the results on iNat2018 and Places-LT. Could you please share the configuration files? Thanks in advance.

**Comment by XuZhengzhuo** [comment]
Hi, you can find the configuration in README or Appendix D3. More detailed records can be found in the table provided in the README, which includes the args / log / ckpt information.

**Comment by ReIDResman** [comment]
Hi, thanks for your response. I found some records you have already provided. But I noticed there are some differences of parameters between Appendix D3 and log information, such as the parameter for Adam. Moreover, through some experiments, I found that effective batch size would somewhat influence the performance. Therefore, I think it is necessary to align the parameters related to it, such as batch size, accumulate iter. 
By the way, could you tell me the number of GPUs you used for training on ImageNet-LT, Places-LT, and iNaturalist 2018 ?

**Comment by XuZhengzhuo** [comment]
Plz keep the parameters consistent with the 'args' configuration and ensure the eff_batch_size >= 2048 when the input size is 224. I used 8 GPUs for the main experiments results and 2 GPUs for the ablation study.

**Comment by ReIDResman** [comment]
Thanks for your quick response. 
Why do you want to ensure that eff_batch_size >= 2048 ? In my experiments, eff_batch_size = 1024 is better when the input size is 224.

**Comment by XuZhengzhuo** [comment]
Actually, we didn't conduct ablation experiments specifically focusing on 'eff_batch_size'. We made this choice to align with previous works like DEiT and MAE.

**Comment by ReIDResman** [comment]
Ok, thank you very much.
